--- #YAML:1.0
name:                Win32-Clipboard
version:             0.57
abstract:            Interaction with the Windows clipboard
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Aldo Calpini <dada@perl.it>, Hideyo Imazu <himazu@gmail.com>, Jan Dubois <jand@activestate.com>
