--- #YAML:1.0
name:               Win32-Clipboard
version:            0.56
abstract:           Interaction with the Windows clipboard
author:
    - Aldo Calpini <dada@perl.it>
    - Hideyo Imazu <himazu@gmail.com>
    - Jan Dubois <jand@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
resources:
    license:     http://dev.perl.org/licenses/
    repository:  https://libwin32.googlecode.com/svn/trunk/Win32-Clipboard
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
